---
language: php

sudo: false

php:
  - '5.3'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit

notifications:
  email: false
