---
language: php

dist: precise

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer install --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - php vendor/bin/codacycoverage clover coverage.xml

notifications:
  email: false
