---
language: php

dist: xenial

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - composer install --no-interaction --dev

script:
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - php bin/codacycoverage clover coverage.xml

notifications:
  email: false
